<div  style="font-size: 13px; line-height: 19px;">
<p><strong>TERMS AND CONDITIONS :</strong></p>
<ol>
  <li>TRANSPORT CHARGES WILL BE BORN BY THE PARTY</li>
  <li>COLLEGE NAME (14 CM X 5 CM SIZE) WILL BE PRINTED IN SINGLE COLOUR ON FOUR COLOUR COVE PAGE FRONT SIDE ONLY</li>
  <li>TITLE PRINTING CHARGE WILL BE FREE WHEN ORDERED AT LEAST 300 BOOKS (IN ALL SUBJECTS OF STUDY MATERIALS)</li>
  <li>ONCE ORDERED BOOKS CAN NOT BE CANCELLED AFTER PRODUCTION CAN BE TAKEN UP</li>
  <li>DELIVERY TIME : MINIMUM ONE WEEK (SUBJECT TO THE AVAILABILITY OF STOCK)</li>
  <li>PAYMENTS SHALL BE MADE BY ONLINE TRANSFER (RTGS/NEFT/ATM/CDM) TO OUR BANK ACCOUNT (OR) DD DRAWN IN FAVOUR OF DEEPTI PUBLICATIONS, TENALI. NO CASH PAYMENTS</li>
  <li>ONLINE TRANSFER PAYMENT HOLDERS MUST SEND A XEROX COPY OF BANK PAY SLIP ON YOUR LETTER HEADS (COLLEGE OR SHOP OR PERSON) BY EMAIL TO <a href="mailto:deeptipublications@gmail.com">deeptipublications@gmail.com</a> TO GET RECEIPT OF THAT PAYMENT</li>
  <li><strong>BANK ACCOUNT DETAILS : 
  </strong>
    <p><strong>ACCOUNT NAME :</strong> DEEPTI PUBLICATIONS<br>
  <strong>ACCOUNT NUMBER :</strong> 451601010014007<br>
  <strong>IFS CODE : </strong>UBIN0545163<br>
  <strong>BANK : </strong>UNION BANK OF INDIA, BRANCH : TENALI</p>
  </li>
</ol>

 </div>